In [1]:
!pip install -q openai pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 45.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.0/345.0 kB 32.2 MB/s eta 0:00:00

In [2]:
!pip install -q transformers accelerate huggingface_hub pandas

In [3]:
import os
import time
import pandas as pd
from openai import OpenAI
from huggingface_hub import login
from transformers import pipeline

In [4]:
API_KEY = "add key"

client = OpenAI(api_key=API_KEY)




questions = [
    "What is the capital of India?",

    "If a train travels 60 kilometers in 1 hour, how far will it travel in 3 hours?",

    "Maria has 5 apples. She gives 2 apples to her friend and buys 3 more. How many apples does she have now?",

    "What is the difference between supervised learning and unsupervised learning?",

    "Write a Python function that checks whether a number is even or odd.",

    "What is the time complexity of searching for an element in a Python list?",

    "If 5 workers can complete a task in 10 days, assuming everyone works at the same rate, how many days would 10 workers take?",

    "Explain what an API is in simple words.",

    "What are the main differences between RAM and ROM?",

    "A shop gives a 20% discount on an item priced at ₹1,000. What is the final price after the discount?"
]

In [4]:


#o3_mini

def ask_o3_mini(question):

    start_time = time.perf_counter()

    response = client.responses.create(
        model="o3-mini",
        input=question
    )

    end_time = time.perf_counter()

    response_time = end_time - start_time

    answer = response.output_text

    return answer, response_time




results = []

for i, question in enumerate(questions, start=1):

    print(f"Processing Question {i}/{len(questions)}...")

    try:
        answer, response_time = ask_o3_mini(question)

        results.append({
            "Question_No": i,
            "Question": question,
            "Model": "o3-mini",
            "Answer": answer,
            "Response_Time_Seconds": round(response_time, 3)
        })

        print(f"Completed in {response_time:.3f} seconds")

    except Exception as e:

        results.append({
            "Question_No": i,
            "Question": question,
            "Model": "o3-mini",
            "Answer": f"ERROR: {str(e)}",
            "Response_Time_Seconds": None
        })

        print(f"Error: {e}")

Processing Question 1/10...
Completed in 5.364 seconds
Processing Question 2/10...
Completed in 2.563 seconds
Processing Question 3/10...
Completed in 2.175 seconds
Processing Question 4/10...
Completed in 2.328 seconds
Processing Question 5/10...
Completed in 6.496 seconds
Processing Question 6/10...
Completed in 3.781 seconds
Processing Question 7/10...
Completed in 2.742 seconds
Processing Question 8/10...
Completed in 1.935 seconds
Processing Question 9/10...
Completed in 4.860 seconds
Processing Question 10/10...
Completed in 2.045 seconds

In [5]:
df = pd.DataFrame(results)



output_file = "o3_mini_results.csv"

df.to_csv(output_file, index=False, encoding="utf-8")

print("\nDone!")
print(f"CSV saved as: {output_file}")



display(df)

Done!
CSV saved as: o3_mini_results.csv

,Question_No,Question,Model,Answer,Response_Time_Seconds
0,1,What is the capital of India?,o3-mini,The capital of India is New Delhi.,5.364
1,2,"If a train travels 60 kilometers in 1 hour, ho...",o3-mini,"If the train travels 60 kilometers in 1 hour, ...",2.563
2,3,Maria has 5 apples. She gives 2 apples to her ...,o3-mini,Maria starts with 5 apples. After giving 2 app...,2.175
3,4,What is the difference between supervised lear...,o3-mini,Supervised learning involves training a model ...,2.328
4,5,Write a Python function that checks whether a ...,o3-mini,Here's a simple Python function that checks wh...,6.496
5,6,What is the time complexity of searching for a...,o3-mini,"In Python, a list is implemented as an array, ...",3.781
6,7,"If 5 workers can complete a task in 10 days, a...",o3-mini,"If 5 workers complete a task in 10 days, then ...",2.742
7,8,Explain what an API is in simple words.,o3-mini,"An API, or Application Programming Interface, ...",1.935
8,9,What are the main differences between RAM and ...,o3-mini,RAM (Random Access Memory) and ROM (Read-Only ...,4.860
9,10,A shop gives a 20% discount on an item priced ...,o3-mini,"The original price of the item is ₹1,000. A 20...",2.045

In [7]:
# gpt-4o-mini

def ask_gpt_4o_mini(question):

    start_time = time.perf_counter()

    response = client.responses.create(
        model="gpt-4o-mini",
        input=question
    )

    end_time = time.perf_counter()

    response_time = end_time - start_time

    answer = response.output_text

    return answer, response_time




results1 = []

for i, question in enumerate(questions, start=1):

    print(f"Processing Question {i}/{len(questions)}...")

    try:
        answer, response_time = ask_gpt_4o_mini(question)

        results1.append({
            "Question_No": i,
            "Question": question,
            "Model": "gpt-4o-mini",
            "Answer": answer,
            "Response_Time_Seconds": round(response_time, 3)
        })

        print(f"Completed in {response_time:.3f} seconds")

    except Exception as e:

        results1.append({
            "Question_No": i,
            "Question": question,
            "Model": "gpt-4o-mini",
            "Answer": f"ERROR: {str(e)}",
            "Response_Time_Seconds": None
        })

        print(f"Error: {e}")

Processing Question 1/10...
Completed in 1.382 seconds
Processing Question 2/10...
Completed in 2.236 seconds
Processing Question 3/10...
Completed in 2.958 seconds
Processing Question 4/10...
Completed in 4.158 seconds
Processing Question 5/10...
Completed in 2.393 seconds
Processing Question 6/10...
Completed in 2.097 seconds
Processing Question 7/10...
Completed in 3.961 seconds
Processing Question 8/10...
Completed in 1.717 seconds
Processing Question 9/10...
Completed in 5.863 seconds
Processing Question 10/10...
Completed in 2.354 seconds

In [8]:
df = pd.DataFrame(results1)



output_file = "gpt_4o_mini_results.csv"

df.to_csv(output_file, index=False, encoding="utf-8")

print("\nDone!")
print(f"CSV saved as: {output_file}")



display(df)

Done!
CSV saved as: gpt_4o_mini_results.csv

,Question_No,Question,Model,Answer,Response_Time_Seconds
0,1,What is the capital of India?,gpt-4o-mini,The capital of India is New Delhi.,1.382
1,2,"If a train travels 60 kilometers in 1 hour, ho...",gpt-4o-mini,"If a train travels 60 kilometers in 1 hour, it...",2.236
2,3,Maria has 5 apples. She gives 2 apples to her ...,gpt-4o-mini,Maria starts with 5 apples. She gives away 2 a...,2.958
3,4,What is the difference between supervised lear...,gpt-4o-mini,Supervised learning and unsupervised learning ...,4.158
4,5,Write a Python function that checks whether a ...,gpt-4o-mini,Here’s a simple Python function that checks wh...,2.393
5,6,What is the time complexity of searching for a...,gpt-4o-mini,The time complexity of searching for an elemen...,2.097
6,7,"If 5 workers can complete a task in 10 days, a...",gpt-4o-mini,To find out how many days 10 workers would tak...,3.961
7,8,Explain what an API is in simple words.,gpt-4o-mini,"An API, or Application Programming Interface, ...",1.717
8,9,What are the main differences between RAM and ...,gpt-4o-mini,RAM (Random Access Memory) and ROM (Read-Only ...,5.863
9,10,A shop gives a 20% discount on an item priced ...,gpt-4o-mini,To calculate the final price after a 20% disco...,2.354

In [ ]:
hf_token = ""

if hf_token is None:
    raise ValueError("HF_TOKEN not found. Add your Hugging Face token to Colab Secrets.")

login(token=hf_token)

model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"

pipe = pipeline(
    "text-generation",
    model=model_name,
    device_map="auto",
    dtype="auto"
)


def ask_deepseek(prompt):

    start_time = time.perf_counter()

    response = pipe(
        prompt,
        max_new_tokens=300,
        temperature=0.6,
        do_sample=True
    )

    end_time = time.perf_counter()

    response_time = end_time - start_time

    answer = response[0]["generated_text"]

    return answer, response_time


results2 = []

for i, question in enumerate(questions, start=1):

    print(f"Processing Question {i}/{len(questions)}...")

    try:

        answer, response_time = ask_deepseek(question)

        results2.append({
            "Question_No": i,
            "Question": question,
            "Model": "DeepSeek-R1-Distill-Qwen-7B",
            "Answer": answer,
            "Response_Time_Seconds": round(response_time, 3)
        })

        print(f"Response time: {response_time:.3f} seconds")
        print("-" * 60)

    except Exception as e:

        results2.append({
            "Question_No": i,
            "Question": question,
            "Model": "DeepSeek-R1-Distill-Qwen-7B",
            "Answer": f"ERROR: {str(e)}",
            "Response_Time_Seconds": None
        })

        print(f"Error: {e}")

config.json:   0%|          | 0.00/680 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/28.1k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.07k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'do_sample', 'temperature', 'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.

Processing Question 1/10...

[transformers] Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
[transformers] Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response time: 25.996 seconds
------------------------------------------------------------
Processing Question 2/10...

[transformers] Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response time: 250.818 seconds
------------------------------------------------------------
Processing Question 3/10...

[transformers] Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response time: 229.690 seconds
------------------------------------------------------------
Processing Question 4/10...

[transformers] Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response time: 238.898 seconds
------------------------------------------------------------
Processing Question 5/10...

[transformers] Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response time: 248.899 seconds
------------------------------------------------------------
Processing Question 6/10...

[transformers] Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response time: 225.992 seconds
------------------------------------------------------------
Processing Question 7/10...

[transformers] Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response time: 211.506 seconds
------------------------------------------------------------
Processing Question 8/10...

[transformers] Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response time: 245.694 seconds
------------------------------------------------------------
Processing Question 9/10...

[transformers] Both `max_new_tokens` (=300) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response time: 247.127 seconds
------------------------------------------------------------
Processing Question 10/10...
Response time: 249.482 seconds
------------------------------------------------------------

In [6]:
df = pd.DataFrame(results2)

output_file = "deepseek_r1_results.csv"

df.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)


print("All 10 questions completed!")

display(df)

All 10 questions completed!

,Question_No,Question,Model,Answer,Response_Time_Seconds
0,1,What is the capital of India?,DeepSeek-R1-Distill-Qwen-7B,What is the capital of India? The capital of I...,25.996
1,2,"If a train travels 60 kilometers in 1 hour, ho...",DeepSeek-R1-Distill-Qwen-7B,"If a train travels 60 kilometers in 1 hour, ho...",250.818
2,3,Maria has 5 apples. She gives 2 apples to her ...,DeepSeek-R1-Distill-Qwen-7B,Maria has 5 apples. She gives 2 apples to her ...,229.690
3,4,What is the difference between supervised lear...,DeepSeek-R1-Distill-Qwen-7B,What is the difference between supervised lear...,238.898
4,5,Write a Python function that checks whether a ...,DeepSeek-R1-Distill-Qwen-7B,Write a Python function that checks whether a ...,248.899
5,6,What is the time complexity of searching for a...,DeepSeek-R1-Distill-Qwen-7B,What is the time complexity of searching for a...,225.992
6,7,"If 5 workers can complete a task in 10 days, a...",DeepSeek-R1-Distill-Qwen-7B,"If 5 workers can complete a task in 10 days, a...",211.506
7,8,Explain what an API is in simple words.,DeepSeek-R1-Distill-Qwen-7B,Explain what an API is in simple words.8. What...,245.694
8,9,What are the main differences between RAM and ...,DeepSeek-R1-Distill-Qwen-7B,What are the main differences between RAM and ...,247.127
9,10,A shop gives a 20% discount on an item priced ...,DeepSeek-R1-Distill-Qwen-7B,A shop gives a 20% discount on an item priced ...,249.482