In [3]:
!pip install -q openai pandas openpyxl

In [4]:
import pandas as pd
import time
import re
from openai import OpenAI
from google.colab import files

In [6]:
uploaded = files.upload()

input_file = list(uploaded.keys())[0]

df = pd.read_csv(input_file)

print("File loaded:", input_file)
print("Columns:", df.columns.tolist())
print("Number of questions:", len(df))


if "question" not in df.columns:
    raise ValueError(
        "Column 'question' not found. Available columns: "
        + str(df.columns.tolist())
    )



if "answer" not in df.columns:
    raise ValueError(
        "Accuracy cannot be calculated because an 'answer' column "
        "was not found.\nAvailable columns: "
        + str(df.columns.tolist())
    )

Saving gsm8k_style_50_questions_answers.csv to gsm8k_style_50_questions_answers (1).csv
File loaded: gsm8k_style_50_questions_answers (1).csv
Columns: ['question_id', 'question', 'answer']
Number of questions: 50

In [7]:
API_KEY = "key"

client = OpenAI(api_key=API_KEY)

In [8]:
def extract_number(text):

    # Remove commas from numbers such as 1,000
    text = text.replace(",", "")

    # Look for common answer patterns first
    patterns = [
        r"(?:final answer|answer)\s*(?:is|:)?\s*\$?(-?\d+(?:\.\d+)?)",
        r"####\s*\$?(-?\d+(?:\.\d+)?)"
    ]

    for pattern in patterns:
        matches = re.findall(pattern, text, flags=re.IGNORECASE)

        if matches:
            return matches[-1]

    # If no explicit answer is found,
    # take the last number in the response
    numbers = re.findall(r"-?\d+(?:\.\d+)?", text)

    if numbers:
        return numbers[-1]

    return None

In [9]:
def ask_o3_mini(question):

    prompt = f"""
Solve the following GSM8K math problem.

Show your reasoning briefly and then provide the final answer.

At the very end, write the answer in this exact format:

FINAL ANSWER: <number>

Question:
{question}
"""

    start_time = time.perf_counter()

    response = client.responses.create(
        model="o3-mini",
        input=prompt
    )

    end_time = time.perf_counter()

    response_time = end_time - start_time

    full_response = response.output_text

    model_answer = extract_number(full_response)

    return full_response, model_answer, response_time

##

results = []

for i, row in df.iterrows():

    question_no = i + 1
    question = str(row["question"])
    correct_answer = str(row["answer"]).strip()

    print(f"\nProcessing {question_no}/{len(df)}")

    try:

        full_response, model_answer, response_time = ask_o3_mini(question)

        # Normalize answers before comparison
        correct_normalized = correct_answer.replace(",", "").strip()
        model_normalized = str(model_answer).replace(",", "").strip()

        # Compare numerically where possible
        try:
            is_correct = float(model_normalized) == float(correct_normalized)
        except:
            is_correct = model_normalized == correct_normalized

        results.append({
            "Question_No": question_no,
            "Question": question,
            "Correct_Answer": correct_answer,
            "Model": "o3-mini",
            "Model_Answer": model_answer,
            "Is_Correct": is_correct,
            "Response_Time_Seconds": round(response_time, 3),
            "Full_Response": full_response
        })

        print("Correct Answer :", correct_answer)
        print("Model Answer   :", model_answer)
        print("Correct?       :", is_correct)
        print("Time           :", round(response_time, 3), "seconds")

    except Exception as e:

        results.append({
            "Question_No": question_no,
            "Question": question,
            "Correct_Answer": correct_answer,
            "Model": "o3-mini",
            "Model_Answer": None,
            "Is_Correct": False,
            "Response_Time_Seconds": None,
            "Full_Response": f"ERROR: {str(e)}"
        })

        print("ERROR:", e)


# ==

results_df = pd.DataFrame(results)


# ===

total_questions = len(results_df)

correct_count = results_df["Is_Correct"].sum()

incorrect_count = total_questions - correct_count

accuracy = (correct_count / total_questions) * 100

average_time = results_df["Response_Time_Seconds"].mean()


# ====

print("\n")
print("=" * 60)
print("             GSM8K MODEL SCORECARD")
print("=" * 60)

print(f"Model              : o3-mini")
print(f"Total Questions    : {total_questions}")
print(f"Correct Answers    : {correct_count}")
print(f"Incorrect Answers  : {incorrect_count}")
print(f"Accuracy           : {accuracy:.2f}%")
print(f"Average Response   : {average_time:.3f} seconds")

print("=" * 60)


# ====

output_file = "gsm8k_o3_mini_results.csv"

results_df.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)


# ====

display(results_df)

files.download(output_file)

Processing 1/50
Correct Answer : 32
Model Answer   : 32
Correct?       : True
Time           : 8.032 seconds

Processing 2/50
Correct Answer : 41
Model Answer   : 41
Correct?       : True
Time           : 1.464 seconds

Processing 3/50
Correct Answer : 78
Model Answer   : 78
Correct?       : True
Time           : 1.553 seconds

Processing 4/50
Correct Answer : 8
Model Answer   : 8
Correct?       : True
Time           : 2.712 seconds

Processing 5/50
Correct Answer : 16
Model Answer   : 16
Correct?       : True
Time           : 3.87 seconds

Processing 6/50
Correct Answer : 183
Model Answer   : 183
Correct?       : True
Time           : 2.278 seconds

Processing 7/50
Correct Answer : 30
Model Answer   : 30
Correct?       : True
Time           : 2.088 seconds

Processing 8/50
Correct Answer : 12
Model Answer   : 12
Correct?       : True
Time           : 3.501 seconds

Processing 9/50
Correct Answer : 32
Model Answer   : 32
Correct?       : True
Time           : 1.68 seconds

Processing 10/50
Correct Answer : 82
Model Answer   : 82
Correct?       : True
Time           : 1.995 seconds

Processing 11/50
Correct Answer : 7
Model Answer   : 7
Correct?       : True
Time           : 3.615 seconds

Processing 12/50
Correct Answer : 150
Model Answer   : 150
Correct?       : True
Time           : 1.931 seconds

Processing 13/50
Correct Answer : 285
Model Answer   : 285
Correct?       : True
Time           : 1.499 seconds

Processing 14/50
Correct Answer : 28
Model Answer   : 28
Correct?       : True
Time           : 2.772 seconds

Processing 15/50
Correct Answer : 240
Model Answer   : 240
Correct?       : True
Time           : 5.79 seconds

Processing 16/50
Correct Answer : 12
Model Answer   : 12
Correct?       : True
Time           : 2.034 seconds

Processing 17/50
Correct Answer : 95
Model Answer   : 95
Correct?       : True
Time           : 1.991 seconds

Processing 18/50
Correct Answer : 125
Model Answer   : 125
Correct?       : True
Time           : 2.361 seconds

Processing 19/50
Correct Answer : 750
Model Answer   : 750
Correct?       : True
Time           : 1.397 seconds

Processing 20/50
Correct Answer : 3
Model Answer   : 3
Correct?       : True
Time           : 1.795 seconds

Processing 21/50
Correct Answer : 30
Model Answer   : 30
Correct?       : True
Time           : 1.823 seconds

Processing 22/50
Correct Answer : 32
Model Answer   : 32
Correct?       : True
Time           : 1.83 seconds

Processing 23/50
Correct Answer : 150
Model Answer   : 150
Correct?       : True
Time           : 2.262 seconds

Processing 24/50
Correct Answer : 4:45 PM
Model Answer   : 4
Correct?       : False
Time           : 1.782 seconds

Processing 25/50
Correct Answer : 6
Model Answer   : 6
Correct?       : True
Time           : 1.346 seconds

Processing 26/50
Correct Answer : 105
Model Answer   : 105
Correct?       : True
Time           : 1.963 seconds

Processing 27/50
Correct Answer : 243
Model Answer   : 243
Correct?       : True
Time           : 1.815 seconds

Processing 28/50
Correct Answer : 54
Model Answer   : 54
Correct?       : True
Time           : 4.944 seconds

Processing 29/50
Correct Answer : 16
Model Answer   : 16
Correct?       : True
Time           : 2.047 seconds

Processing 30/50
Correct Answer : 60
Model Answer   : 60
Correct?       : True
Time           : 3.191 seconds

Processing 31/50
Correct Answer : 180
Model Answer   : 180
Correct?       : True
Time           : 2.74 seconds

Processing 32/50
Correct Answer : 100
Model Answer   : 100
Correct?       : True
Time           : 7.209 seconds

Processing 33/50
Correct Answer : 115
Model Answer   : 115
Correct?       : True
Time           : 1.826 seconds

Processing 34/50
Correct Answer : 110
Model Answer   : 110
Correct?       : True
Time           : 2.152 seconds

Processing 35/50
Correct Answer : 103
Model Answer   : 103
Correct?       : True
Time           : 2.234 seconds

Processing 36/50
Correct Answer : 198
Model Answer   : 198
Correct?       : True
Time           : 1.742 seconds

Processing 37/50
Correct Answer : 300
Model Answer   : 300
Correct?       : True
Time           : 2.507 seconds

Processing 38/50
Correct Answer : 195
Model Answer   : 195
Correct?       : True
Time           : 1.868 seconds

Processing 39/50
Correct Answer : 115
Model Answer   : 40
Correct?       : False
Time           : 1.418 seconds

Processing 40/50
Correct Answer : 40
Model Answer   : 31
Correct?       : False
Time           : 1.96 seconds

Processing 41/50
Correct Answer : 31
Model Answer   : 336
Correct?       : False
Time           : 1.796 seconds

Processing 42/50
Correct Answer : 336
Model Answer   : 500
Correct?       : False
Time           : 2.113 seconds

Processing 43/50
Correct Answer : 240
Model Answer   : 13
Correct?       : False
Time           : 2.566 seconds

Processing 44/50
Correct Answer : 13
Model Answer   : 10
Correct?       : False
Time           : 1.981 seconds

Processing 45/50
Correct Answer : 10
Model Answer   : 60
Correct?       : False
Time           : 1.714 seconds

Processing 46/50
Correct Answer : 60
Model Answer   : 80
Correct?       : False
Time           : 1.785 seconds

Processing 47/50
Correct Answer : 80
Model Answer   : 115
Correct?       : False
Time           : 8.135 seconds

Processing 48/50
Correct Answer : 67
Model Answer   : 150
Correct?       : False
Time           : 1.868 seconds

Processing 49/50
Correct Answer : 150
Model Answer   : 2400
Correct?       : False
Time           : 1.932 seconds

Processing 50/50
Correct Answer : 500
Model Answer   : 500
Correct?       : True
Time           : 2.658 seconds


============================================================
             GSM8K MODEL SCORECARD
============================================================
Model              : o3-mini
Total Questions    : 50
Correct Answers    : 38
Incorrect Answers  : 12
Accuracy           : 76.00%
Average Response   : 2.591 seconds
============================================================

,Question_No,Question,Correct_Answer,Model,Model_Answer,Is_Correct,Response_Time_Seconds,Full_Response
0,1,Sarah has 24 apples. She gives 7 to her brothe...,32,o3-mini,32,True,8.032,"Starting with 24 apples, Sarah gives 7 away, l..."
1,2,A farmer has 35 chickens. He buys 18 more and ...,41,o3-mini,41,True,1.464,The farmer starts with 35 chickens. After buyi...
2,3,Tom reads 12 pages every day for 5 days. He th...,78,o3-mini,78,True,1.553,"Tom reads 12 pages per day for 5 days, which t..."
3,4,A box contains 48 pencils. The pencils are div...,8,o3-mini,8,True,2.712,We need to divide 48 pencils equally among 6 s...
4,5,Maria buys 4 notebooks at $3 each and 2 pens a...,16,o3-mini,16,True,3.870,"Maria buys 4 notebooks at $3 each, which costs..."
5,6,A school has 8 classrooms. Each classroom has ...,183,o3-mini,183,True,2.278,"There are 8 classrooms with 25 students each, ..."
6,7,John has $60. He spends $18 on a shirt and $12...,30,o3-mini,30,True,2.088,John starts with $60. He spends $18 on a shirt...
7,8,A baker makes 120 cookies. He packs them equal...,12,o3-mini,12,True,3.501,The baker packs the cookies evenly into 10 box...
8,9,Lisa walks 3 kilometers in the morning and 5 k...,32,o3-mini,32,True,1.680,Lisa walks 3 km in the morning and 5 km in the...
9,10,A store has 75 red balloons and 45 blue balloo...,82,o3-mini,82,True,1.995,"To solve, first add the red and blue balloons:..."
10,11,A farmer collects 84 eggs and puts 12 eggs in ...,7,o3-mini,7,True,3.615,"To solve the problem, we divide the total numb..."
11,12,David earns $15 per hour. He works 6 hours on ...,150,o3-mini,150,True,1.931,David works a total of 6 + 4 = 10 hours. Since...
12,13,A library has 250 books. It receives 75 new bo...,285,o3-mini,285,True,1.499,The library starts with 250 books. After recei...
13,14,Emma has 5 bags containing 8 candies each. She...,28,o3-mini,28,True,2.772,"First, calculate the total candies: 5 bags × 8..."
14,15,A train travels 60 kilometers per hour for 4 h...,240,o3-mini,240,True,5.790,"The train travels at 60 km/h for 4 hours. So, ..."
15,16,A teacher has 96 stickers and wants to distrib...,12,o3-mini,12,True,2.034,"To solve the problem, divide the total number ..."
16,17,A restaurant prepares 150 sandwiches. During l...,95,o3-mini,95,True,1.991,The restaurant started with 150 sandwiches. Af...
17,18,Mike saves $20 every week for 8 weeks. He then...,125,o3-mini,125,True,2.361,"Mike saves 20 dollars per week for 8 weeks, wh..."
18,19,A factory produces 125 toys each day. How many...,750,o3-mini,750,True,1.397,The factory produces 125 toys per day. In 6 da...
19,20,There are 72 students going on a trip. Each bu...,3,o3-mini,3,True,1.795,We need to determine how many buses are requir...
20,21,A fruit seller has 40 oranges. He sells 25% of...,30,o3-mini,30,True,1.823,The seller has 40 oranges and sells 25% of the...
21,22,A shirt costs $40. It is discounted by $8. Wha...,32,o3-mini,32,True,1.830,The original price is $40. After subtracting t...
22,23,A farmer has 6 fields. Each field produces 45 ...,150,o3-mini,150,True,2.262,The farmer's total production is 6 fields × 45...
23,24,A movie starts at 2:30 PM and lasts 2 hours an...,4:45 PM,o3-mini,4,False,1.782,We start at 2:30 PM. Adding 2 hours brings us ...
24,25,A shop sells pencils for $2 each. A customer b...,6,o3-mini,6,True,1.346,The cost of 7 pencils at $2 each is 7 × 2 = $1...
25,26,A family uses 15 liters of water each day. How...,105,o3-mini,105,True,1.963,The family uses 15 liters of water per day and...
26,27,There are 9 shelves in a library. Each shelf h...,243,o3-mini,243,True,1.815,"First, calculate the total number of books: 9 ..."
27,28,A cyclist travels 18 kilometers in the morning...,54,o3-mini,54,True,4.944,The cyclist travels 18 km in the morning and t...
28,29,A class has 40 students. 60% of the students a...,16,o3-mini,16,True,2.047,"There are 40 students in the class, and 60% of..."
29,30,A farmer has 150 kilograms of rice. He packs i...,60,o3-mini,60,True,3.191,"First, calculate the total weight of rice sold..."
30,31,A company has 240 employees. One-quarter of th...,180,o3-mini,180,True,2.740,One-quarter of 240 equals 60 employees working...
31,32,A store receives 300 bottles. It sells 40 bott...,100,o3-mini,100,True,7.209,The store sells 40 bottles each day for 5 days...
32,33,Anna buys 3 dresses for $25 each. She also buy...,115,o3-mini,115,True,1.826,"Anna buys 3 dresses at $25 each, which totals ..."
33,34,A school orders 15 boxes of pencils. Each box ...,110,o3-mini,110,True,2.152,"First, calculate the total number of pencils: ..."
34,35,A farmer plants 8 rows of trees with 15 trees ...,103,o3-mini,103,True,2.234,"First, the farmer plants 8 rows with 15 trees ..."
35,36,A worker earns $18 per hour for the first 8 ho...,198,o3-mini,198,True,1.742,The worker earns 18 dollars per hour for the f...
36,37,A water tank contains 500 liters. A family use...,300,o3-mini,300,True,2.507,The tank starts with 500 liters. The family us...
37,38,"A bookstore sells 45 books on Monday, 60 on Tu...",195,o3-mini,195,True,1.868,"First, calculate the number of books sold on W..."
38,39,A class collects $480 for a charity. They divi...,115,o3-mini,40,False,1.418,We start by dividing 480 by 12 to see how much...
39,40,A car has a fuel tank that holds 60 liters. It...,40,o3-mini,31,False,1.960,Start with 18 liters. Add 25 liters: 18 + 25 =...
40,41,A farmer has 4 cows. Each cow produces 12 lite...,31,o3-mini,336,False,1.796,Each cow produces 12 liters per day. With 4 co...
41,42,A school has 5 grades. Each grade has 4 classe...,336,o3-mini,500,False,2.113,"There are 5 grades, each with 4 classes, and e..."
42,43,A family buys 6 pizzas. Each pizza is cut into...,240,o3-mini,13,False,2.566,"Each pizza has 8 slices, so with 6 pizzas ther..."
43,44,A company ships 360 packages equally among 9 t...,13,o3-mini,10,False,1.981,"First, divide the 360 packages equally among 9..."
44,45,A shop buys a phone for $200 and sells it for ...,10,o3-mini,60,False,1.714,"To compute the profit, subtract the cost price..."
45,46,"A student gets scores of 75, 82, 91, and 72 on...",60,o3-mini,80,False,1.785,"To find the average, add the scores: 75 + 82 +..."
46,47,A farmer has 240 apples. He puts 20% into stor...,80,o3-mini,115,False,8.135,"The farmer starts with 240 apples. First, he p..."
47,48,"A bus travels 45 kilometers in its first hour,...",67,o3-mini,150,False,1.868,"The bus travels 45 km in the first hour, 55 km..."
48,49,A factory has 5 machines. Each machine produce...,150,o3-mini,2400,False,1.932,We first calculate the total number of items p...
49,50,"A family has a monthly budget of $2,000. They ...",500,o3-mini,500,True,2.658,The total monthly expenses are $750 (rent) + $...

In [11]:
def ask_gpt_o4_mini(question):

    prompt = f"""
Solve the following GSM8K math problem.

Show your reasoning briefly and then provide the final answer.

At the very end, write the answer in this exact format:

FINAL ANSWER: <number>

Question:
{question}
"""

    start_time = time.perf_counter()

    response = client.responses.create(
        model="gpt-4o-mini",
        input=prompt
    )

    end_time = time.perf_counter()

    response_time = end_time - start_time

    full_response = response.output_text

    model_answer = extract_number(full_response)

    return full_response, model_answer, response_time

##

results = []

for i, row in df.iterrows():

    question_no = i + 1
    question = str(row["question"])
    correct_answer = str(row["answer"]).strip()

    print(f"\nProcessing {question_no}/{len(df)}")

    try:

        full_response, model_answer, response_time = ask_gpt_o4_mini(question)

        # Normalize answers before comparison
        correct_normalized = correct_answer.replace(",", "").strip()
        model_normalized = str(model_answer).replace(",", "").strip()

        # Compare numerically where possible
        try:
            is_correct = float(model_normalized) == float(correct_normalized)
        except:
            is_correct = model_normalized == correct_normalized

        results.append({
            "Question_No": question_no,
            "Question": question,
            "Correct_Answer": correct_answer,
            "Model": "gpt-4o-mini",
            "Model_Answer": model_answer,
            "Is_Correct": is_correct,
            "Response_Time_Seconds": round(response_time, 3),
            "Full_Response": full_response
        })

        print("Correct Answer :", correct_answer)
        print("Model Answer   :", model_answer)
        print("Correct?       :", is_correct)
        print("Time           :", round(response_time, 3), "seconds")

    except Exception as e:

        results.append({
            "Question_No": question_no,
            "Question": question,
            "Correct_Answer": correct_answer,
            "Model": "gpt-4o-mini",
            "Model_Answer": None,
            "Is_Correct": False,
            "Response_Time_Seconds": None,
            "Full_Response": f"ERROR: {str(e)}"
        })

        print("ERROR:", e)


# ==

results_df = pd.DataFrame(results)


# ===

total_questions = len(results_df)

correct_count = results_df["Is_Correct"].sum()

incorrect_count = total_questions - correct_count

accuracy = (correct_count / total_questions) * 100

average_time = results_df["Response_Time_Seconds"].mean()


# ====

print("\n")
print("=" * 60)
print("             GSM8K MODEL SCORECARD")
print("=" * 60)

print(f"Model              : gpt-4o-mini")
print(f"Total Questions    : {total_questions}")
print(f"Correct Answers    : {correct_count}")
print(f"Incorrect Answers  : {incorrect_count}")
print(f"Accuracy           : {accuracy:.2f}%")
print(f"Average Response   : {average_time:.3f} seconds")

print("=" * 60)


# ====

output_file = "gsm8k_gpt_o4_mini_results.csv"

results_df.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)


# ====

display(results_df)

files.download(output_file)

Processing 1/50
Correct Answer : 32
Model Answer   : 32
Correct?       : True
Time           : 2.206 seconds

Processing 2/50
Correct Answer : 41
Model Answer   : 41
Correct?       : True
Time           : 2.847 seconds

Processing 3/50
Correct Answer : 78
Model Answer   : 78
Correct?       : True
Time           : 3.131 seconds

Processing 4/50
Correct Answer : 8
Model Answer   : 8
Correct?       : True
Time           : 2.216 seconds

Processing 5/50
Correct Answer : 16
Model Answer   : 16
Correct?       : True
Time           : 6.2 seconds

Processing 6/50
Correct Answer : 183
Model Answer   : 183
Correct?       : True
Time           : 1.586 seconds

Processing 7/50
Correct Answer : 30
Model Answer   : 30
Correct?       : True
Time           : 3.236 seconds

Processing 8/50
Correct Answer : 12
Model Answer   : 12
Correct?       : True
Time           : 2.109 seconds

Processing 9/50
Correct Answer : 32
Model Answer   : 32
Correct?       : True
Time           : 2.297 seconds

Processing 10/50
Correct Answer : 82
Model Answer   : 82
Correct?       : True
Time           : 2.104 seconds

Processing 11/50
Correct Answer : 7
Model Answer   : 7
Correct?       : True
Time           : 2.05 seconds

Processing 12/50
Correct Answer : 150
Model Answer   : 150
Correct?       : True
Time           : 2.363 seconds

Processing 13/50
Correct Answer : 285
Model Answer   : 285
Correct?       : True
Time           : 2.694 seconds

Processing 14/50
Correct Answer : 28
Model Answer   : 28
Correct?       : True
Time           : 2.369 seconds

Processing 15/50
Correct Answer : 240
Model Answer   : 240
Correct?       : True
Time           : 2.112 seconds

Processing 16/50
Correct Answer : 12
Model Answer   : 12
Correct?       : True
Time           : 1.804 seconds

Processing 17/50
Correct Answer : 95
Model Answer   : 95
Correct?       : True
Time           : 2.079 seconds

Processing 18/50
Correct Answer : 125
Model Answer   : 125
Correct?       : True
Time           : 4.028 seconds

Processing 19/50
Correct Answer : 750
Model Answer   : 750
Correct?       : True
Time           : 3.907 seconds

Processing 20/50
Correct Answer : 3
Model Answer   : 3
Correct?       : True
Time           : 2.19 seconds

Processing 21/50
Correct Answer : 30
Model Answer   : 30
Correct?       : True
Time           : 2.175 seconds

Processing 22/50
Correct Answer : 32
Model Answer   : 32
Correct?       : True
Time           : 2.879 seconds

Processing 23/50
Correct Answer : 150
Model Answer   : 150
Correct?       : True
Time           : 2.481 seconds

Processing 24/50
Correct Answer : 4:45 PM
Model Answer   : 4
Correct?       : False
Time           : 1.617 seconds

Processing 25/50
Correct Answer : 6
Model Answer   : 6
Correct?       : True
Time           : 3.273 seconds

Processing 26/50
Correct Answer : 105
Model Answer   : 105
Correct?       : True
Time           : 2.425 seconds

Processing 27/50
Correct Answer : 243
Model Answer   : 243
Correct?       : True
Time           : 2.988 seconds

Processing 28/50
Correct Answer : 54
Model Answer   : 54
Correct?       : True
Time           : 1.918 seconds

Processing 29/50
Correct Answer : 16
Model Answer   : 16
Correct?       : True
Time           : 1.855 seconds

Processing 30/50
Correct Answer : 60
Model Answer   : 60
Correct?       : True
Time           : 7.736 seconds

Processing 31/50
Correct Answer : 180
Model Answer   : 180
Correct?       : True
Time           : 2.476 seconds

Processing 32/50
Correct Answer : 100
Model Answer   : 100
Correct?       : True
Time           : 2.264 seconds

Processing 33/50
Correct Answer : 115
Model Answer   : 115
Correct?       : True
Time           : 1.927 seconds

Processing 34/50
Correct Answer : 110
Model Answer   : 110
Correct?       : True
Time           : 2.332 seconds

Processing 35/50
Correct Answer : 103
Model Answer   : 103
Correct?       : True
Time           : 2.507 seconds

Processing 36/50
Correct Answer : 198
Model Answer   : 198
Correct?       : True
Time           : 4.28 seconds

Processing 37/50
Correct Answer : 300
Model Answer   : 300
Correct?       : True
Time           : 2.448 seconds

Processing 38/50
Correct Answer : 195
Model Answer   : 195
Correct?       : True
Time           : 2.513 seconds

Processing 39/50
Correct Answer : 115
Model Answer   : 40
Correct?       : False
Time           : 2.801 seconds

Processing 40/50
Correct Answer : 40
Model Answer   : 31
Correct?       : False
Time           : 1.903 seconds

Processing 41/50
Correct Answer : 31
Model Answer   : 336
Correct?       : False
Time           : 3.437 seconds

Processing 42/50
Correct Answer : 336
Model Answer   : 500
Correct?       : False
Time           : 2.285 seconds

Processing 43/50
Correct Answer : 240
Model Answer   : 13
Correct?       : False
Time           : 2.418 seconds

Processing 44/50
Correct Answer : 13
Model Answer   : 10
Correct?       : False
Time           : 2.091 seconds

Processing 45/50
Correct Answer : 10
Model Answer   : 60
Correct?       : False
Time           : 2.002 seconds

Processing 46/50
Correct Answer : 60
Model Answer   : 80
Correct?       : False
Time           : 1.537 seconds

Processing 47/50
Correct Answer : 80
Model Answer   : 67
Correct?       : False
Time           : 2.517 seconds

Processing 48/50
Correct Answer : 67
Model Answer   : 150
Correct?       : False
Time           : 2.335 seconds

Processing 49/50
Correct Answer : 150
Model Answer   : 2400
Correct?       : False
Time           : 2.38 seconds

Processing 50/50
Correct Answer : 500
Model Answer   : 500
Correct?       : True
Time           : 3.336 seconds


============================================================
             GSM8K MODEL SCORECARD
============================================================
Model              : gpt-4o-mini
Total Questions    : 50
Correct Answers    : 38
Incorrect Answers  : 12
Accuracy           : 76.00%
Average Response   : 2.653 seconds
============================================================

,Question_No,Question,Correct_Answer,Model,Model_Answer,Is_Correct,Response_Time_Seconds,Full_Response
0,1,Sarah has 24 apples. She gives 7 to her brothe...,32,gpt-4o-mini,32,True,2.206,"To find out how many apples Sarah has now, we ..."
1,2,A farmer has 35 chickens. He buys 18 more and ...,41,gpt-4o-mini,41,True,2.847,"To solve the problem, we start with the number..."
2,3,Tom reads 12 pages every day for 5 days. He th...,78,gpt-4o-mini,78,True,3.131,"To find the total number of pages Tom read, we..."
3,4,A box contains 48 pencils. The pencils are div...,8,gpt-4o-mini,8,True,2.216,To find out how many pencils each student rece...
4,5,Maria buys 4 notebooks at $3 each and 2 pens a...,16,gpt-4o-mini,16,True,6.200,"To find out how much Maria spends in total, we..."
5,6,A school has 8 classrooms. Each classroom has ...,183,gpt-4o-mini,183,True,1.586,"To find the number of students present, we fir..."
6,7,John has $60. He spends $18 on a shirt and $12...,30,gpt-4o-mini,30,True,3.236,"To find out how much money John has left, we s..."
7,8,A baker makes 120 cookies. He packs them equal...,12,gpt-4o-mini,12,True,2.109,"To find out how many cookies are in each box, ..."
8,9,Lisa walks 3 kilometers in the morning and 5 k...,32,gpt-4o-mini,32,True,2.297,To find out how many kilometers Lisa walks in ...
9,10,A store has 75 red balloons and 45 blue balloo...,82,gpt-4o-mini,82,True,2.104,To find the number of balloons that remain aft...
10,11,A farmer collects 84 eggs and puts 12 eggs in ...,7,gpt-4o-mini,7,True,2.050,To determine how many cartons the farmer can f...
11,12,David earns $15 per hour. He works 6 hours on ...,150,gpt-4o-mini,150,True,2.363,"To find out how much David earns in total, we ..."
12,13,A library has 250 books. It receives 75 new bo...,285,gpt-4o-mini,285,True,2.694,To find out how many books the library has now...
13,14,Emma has 5 bags containing 8 candies each. She...,28,gpt-4o-mini,28,True,2.369,"To determine how many candies Emma has left, w..."
14,15,A train travels 60 kilometers per hour for 4 h...,240,gpt-4o-mini,240,True,2.112,"To find out how far the train travels, we can ..."
15,16,A teacher has 96 stickers and wants to distrib...,12,gpt-4o-mini,12,True,1.804,To find out how many stickers each student rec...
16,17,A restaurant prepares 150 sandwiches. During l...,95,gpt-4o-mini,95,True,2.079,To find out how many sandwiches the restaurant...
17,18,Mike saves $20 every week for 8 weeks. He then...,125,gpt-4o-mini,125,True,4.028,"First, we calculate how much money Mike saves ..."
18,19,A factory produces 125 toys each day. How many...,750,gpt-4o-mini,750,True,3.907,To find out how many toys the factory produces...
19,20,There are 72 students going on a trip. Each bu...,3,gpt-4o-mini,3,True,2.190,To determine how many buses are needed to carr...
20,21,A fruit seller has 40 oranges. He sells 25% of...,30,gpt-4o-mini,30,True,2.175,To find out how many oranges the fruit seller ...
21,22,A shirt costs $40. It is discounted by $8. Wha...,32,gpt-4o-mini,32,True,2.879,To find the final price of the shirt after the...
22,23,A farmer has 6 fields. Each field produces 45 ...,150,gpt-4o-mini,150,True,2.481,"To solve the problem, we first need to determi..."
23,24,A movie starts at 2:30 PM and lasts 2 hours an...,4:45 PM,gpt-4o-mini,4,False,1.617,"To determine the end time of the movie, we tak..."
24,25,A shop sells pencils for $2 each. A customer b...,6,gpt-4o-mini,6,True,3.273,"To find the change the customer receives, we f..."
25,26,A family uses 15 liters of water each day. How...,105,gpt-4o-mini,105,True,2.425,To find out how much water the family uses in ...
26,27,There are 9 shelves in a library. Each shelf h...,243,gpt-4o-mini,243,True,2.988,To find out how many books remain in the libra...
27,28,A cyclist travels 18 kilometers in the morning...,54,gpt-4o-mini,54,True,1.918,"First, we calculate the distance the cyclist t..."
28,29,A class has 40 students. 60% of the students a...,16,gpt-4o-mini,16,True,1.855,"To find the number of boys in the class, we fi..."
29,30,A farmer has 150 kilograms of rice. He packs i...,60,gpt-4o-mini,60,True,7.736,"To solve this problem, we start by calculating..."
30,31,A company has 240 employees. One-quarter of th...,180,gpt-4o-mini,180,True,2.476,To find out how many employees work in the off...
31,32,A store receives 300 bottles. It sells 40 bott...,100,gpt-4o-mini,100,True,2.264,To find out how many bottles are left after se...
32,33,Anna buys 3 dresses for $25 each. She also buy...,115,gpt-4o-mini,115,True,1.927,"First, we calculate the total cost of the dres..."
33,34,A school orders 15 boxes of pencils. Each box ...,110,gpt-4o-mini,110,True,2.332,To find out how many pencils remain after dist...
34,35,A farmer plants 8 rows of trees with 15 trees ...,103,gpt-4o-mini,103,True,2.507,"To find the number of trees still alive, we st..."
35,36,A worker earns $18 per hour for the first 8 ho...,198,gpt-4o-mini,198,True,4.280,To calculate the worker's total earnings for t...
36,37,A water tank contains 500 liters. A family use...,300,gpt-4o-mini,300,True,2.448,To find out how many liters remain in the wate...
37,38,"A bookstore sells 45 books on Monday, 60 on Tu...",195,gpt-4o-mini,195,True,2.513,Let's break it down day by day:\n\n- **Monday:...
38,39,A class collects $480 for a charity. They divi...,115,gpt-4o-mini,40,False,2.801,To determine how much each organization receiv...
39,40,A car has a fuel tank that holds 60 liters. It...,40,gpt-4o-mini,31,False,1.903,To determine how much fuel is left in the tank...
40,41,A farmer has 4 cows. Each cow produces 12 lite...,31,gpt-4o-mini,336,False,3.437,To find the total milk production of the cows ...
41,42,A school has 5 grades. Each grade has 4 classe...,336,gpt-4o-mini,500,False,2.285,To determine the total number of students in t...
42,43,A family buys 6 pizzas. Each pizza is cut into...,240,gpt-4o-mini,13,False,2.418,"To find out how many slices are left, we start..."
43,44,A company ships 360 packages equally among 9 t...,13,gpt-4o-mini,10,False,2.091,"To solve this problem, we need to follow these..."
44,45,A shop buys a phone for $200 and sells it for ...,10,gpt-4o-mini,60,False,2.002,"To find the profit, we subtract the cost price..."
45,46,"A student gets scores of 75, 82, 91, and 72 on...",60,gpt-4o-mini,80,False,1.537,"To find the average score, we need to add all ..."
46,47,A farmer has 240 apples. He puts 20% into stor...,80,gpt-4o-mini,67,False,2.517,"To solve the problem, we follow these steps:\n..."
47,48,"A bus travels 45 kilometers in its first hour,...",67,gpt-4o-mini,150,False,2.335,To find the total distance traveled by the bus...
48,49,A factory has 5 machines. Each machine produce...,150,gpt-4o-mini,2400,False,2.380,To find the total number of items produced by ...
49,50,"A family has a monthly budget of $2,000. They ...",500,gpt-4o-mini,500,True,3.336,To find out how much money remains in the fami...